### Python libraries for datascience
- organizing,processing,analysing the huge amount data.
- apply data visulization
- extracting the data from sourse.
- nearly 20 python libraries for datascience.

#### top3
- numpy
- pandas
- matplotlib

### Numpy(num+py)
- numericaldata+python
- it is a fundamental package for scientific computing in python.
- numpy is the python library
- it used to create multidimential arrys for fast operations
    - its dealing with mathematical,scientific,statical data.
- numpy contains a powerful n-dimension array object.which in the form of row and columns.
- we can initilize numpy arrays from nested python lists

In [ ]:
#how to install numpy
- pip install numpy

In [1]:
#how to import and use numpy package
import numpy as np

In [25]:
#how to find the numpy version
np.__version__

'1.18.5'

In [6]:
#how to create numpy arrays?
import numpy as np
a=np.array([1,2,3,4])  #single-dimensional numpy array
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [12]:
a2=np.array([[2,3,4],[4,5,6]])
print(a2)  #2dimensinal numpy array
print(type(a2))

[[2 3 4]
 [4 5 6]]
<class 'numpy.ndarray'>


In [14]:
#to know the shape of array
a2.shape

(2, 3)

In [17]:
li=[2,3,4,'h','i']
print(type(li))
a1=np.array(li)
print(a1)
print(type(a1))

<class 'list'>
['2' '3' '4' 'h' 'i']
<class 'numpy.ndarray'>


In [18]:
ar=np.array([[1,2],[3,4],[5,6]])
print(ar)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
print(ar.dtype)

int32


In [20]:
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [21]:
print(b.shape)

(2, 2)


In [22]:
b.size

4

In [23]:
b.itemsize

4

In [24]:
b.ndim

2

In [34]:
#range()
a=np.array(range(10))
print(a)
print(type(a))
print(a.shape)
print(a.size)
b=np.array(range(1,10,2))
print(b)
print(b.ndim)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)
10
[1 3 5 7 9]
1


In [35]:
#arange()-third party of numpy library
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a=np.arange(1,20,3)
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [41]:
x=np.arange(10)
print(x.reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [46]:
#reshape of array
a1=np.array([1,2,3,4,5,6,7,8])
print(a1.shape)
print("before reshape",a1)
print(a1.ndim)
a2=a1.reshape(4,2)
print("after reshape",a2)
print(a2.shape)
print(a2.ndim)

(8,)
before reshape [1 2 3 4 5 6 7 8]
1
after reshape [[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
2


In [57]:
#resize of array(its modifies shape and array itself)
a1=np.array([1,2,3,4,5,6,7,8])
print(a1)
print(a1.shape)
a1.resize(3)  #resize the no of elements from original array
print(a1)
print(a1.shape)
a1.resize(2,4)
print(a1)
print(a1.shape)
a1.resize(3,3)
print(a1)
print(a1.shape)

[1 2 3 4 5 6 7 8]
(8,)
[1 2 3]
(3,)
[[1 2 3 0]
 [0 0 0 0]]
(2, 4)
[[1 2 3]
 [0 0 0]
 [0 0 0]]
(3, 3)


In [62]:
#zero array
import numpy as np
a1=np.zeros(3)
a2=np.zeros((2,4),dtype="int64")
print(a1.dtype)
print(a2.dtype)
print(a1)
print(a2)

float64
int64
[0. 0. 0.]
[[0 0 0 0]
 [0 0 0 0]]


In [67]:
#one array
a2=np.ones(3,dtype="int64")
print(a2)
np.ones((6,5),dtype="int64")

[1 1 1]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [68]:
#full array-full(dimension,specified number)
a=np.full((3,3),7)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [75]:
np.diag(a)

array([7, 7, 7])

In [69]:
np.full(3,100)

array([100, 100, 100])

In [70]:
np.full((3,9),500)

array([[500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500]])

In [71]:
#eye array
np.eye(6,dtype="int64")

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]], dtype=int64)

In [73]:
n=np.eye(5)
n

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
np.diag(n)

array([1., 1., 1., 1., 1.])

In [79]:
r=np.random.randint(1,10)
r

5

In [80]:
s=np.random.randint(1,19,12).reshape(3,4)
s

array([[ 1,  9, 13,  3],
       [16,  6, 11,  6],
       [17, 15,  6, 11]])

In [81]:
np.diag(s)

array([1, 6, 6])

In [91]:
p=np.random.random((6)).reshape(2,3)
p

array([[0.83880857, 0.76473981, 0.24504448],
       [0.38927107, 0.19407476, 0.58122448]])

In [103]:
f=np.random.randn(2,3)
f

array([[ 0.27302241, -0.6913019 ,  0.65991599],
       [ 0.2875314 ,  0.44815457, -0.93992438]])

In [109]:
a=np.random.randint(1,30,(10,3))
a

array([[14, 24,  1],
       [ 3, 16,  5],
       [29, 15, 10],
       [14,  3, 29],
       [ 8,  4, 29],
       [11, 20, 17],
       [27, 10,  9],
       [ 1, 20, 27],
       [18, 28, 15],
       [ 1, 16, 23]])

In [110]:
a[1:5]

array([[ 3, 16,  5],
       [29, 15, 10],
       [14,  3, 29],
       [ 8,  4, 29]])

In [111]:
a[2:,:2]

array([[29, 15],
       [14,  3],
       [ 8,  4],
       [11, 20],
       [27, 10],
       [ 1, 20],
       [18, 28],
       [ 1, 16]])

In [112]:
a

array([[14, 24,  1],
       [ 3, 16,  5],
       [29, 15, 10],
       [14,  3, 29],
       [ 8,  4, 29],
       [11, 20, 17],
       [27, 10,  9],
       [ 1, 20, 27],
       [18, 28, 15],
       [ 1, 16, 23]])

In [113]:
a>10

array([[ True,  True, False],
       [False,  True, False],
       [ True,  True, False],
       [ True, False,  True],
       [False, False,  True],
       [ True,  True,  True],
       [ True, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [114]:
a[a>10]

array([14, 24, 16, 29, 15, 14, 29, 29, 11, 20, 17, 27, 20, 27, 18, 28, 15,
       16, 23])

In [115]:
a[a>10].sum()

392

In [116]:
a.max()

29

In [117]:
a.min()

1

In [118]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [119]:
b=np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [128]:
print(a+b)
print("*************")
print(a-b)
print("______________")
print(a*b)
print("$$$$$$$$$$$$$$")
print(a%b)
print(np.max(a))
print(np.min(b))

[[10 12 14]
 [16 18 20]
 [22 24 26]]
*************
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
______________
[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]
$$$$$$$$$$$$$$
[[0 1 2]
 [3 4 5]
 [6 7 8]]
8
10


In [129]:
# 0 to 15 -->(3,5)
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [130]:
print(np.mean(a))

7.0


In [131]:
np.median(a)

7.0

In [132]:
b.dot(a)

array([[175, 208, 241, 274, 307],
       [220, 262, 304, 346, 388],
       [265, 316, 367, 418, 469]])

In [133]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [134]:
a+3

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17]])

In [135]:
a+10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [136]:
np.log2(2)

1.0

In [137]:
np.log([1,2,3])

array([0.        , 0.69314718, 1.09861229])

In [138]:
np.exp(1)

2.718281828459045

In [139]:
np.sin(0)

0.0

In [141]:
np.sin(30)

-0.9880316240928618

In [142]:
np.cos(0)

1.0

In [143]:
np.tan(30)

-6.405331196646276

In [146]:
import numpy
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad